version: "2"
services:
  postgres:
    image: postgres
    container_name: gosaml_postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - go-saml

networks:
  go-saml:
